Update main.yml

diff --git a/main.yml b/main.yml
--- a/main.yml
+++ b/main.yml
@@ -38,7 +38,13 @@ jobs:
 
     - name: Verify flet installation
       run: |
-        flet --version  # التحقق من تثبيت مكتبة flet
+        if ! command -v flet &> /dev/null
+        then
+          echo "flet could not be found"
+          exit 1
+        else
+          flet --version  # التحقق من تثبيت مكتبة flet
+        fi
 
     - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
       uses: subosito/flutter-action@v2
@@ -73,4 +79,3 @@ jobs:
 
     - name: Clean Up
       run: flutter clean
-
